### ISSUE TITLE
Doesn't seem to work on forge 1.18.1 server

### ISSUE THREAD

**Issue by EJFores** [holmraven/ChickensShed#1]
Problem: Feathers do not drop from chickens anymore but only on a dedicated server. They still drop eggs. In singleplayer it works fine. 
Current Forge Version: 39.0.55
Chicken Shed Version: 1.3.1
Cloth Config Version: 6.1.50

Note: I am playing with other mods, however nothing that would affect mob logic. Please let me know if you want a list of the mods on the server anyway.

**Comment by holmraven** [comment]
Hello, unfortunately I was unable to replicate your issue, it seems to be working fine on my side. Could you please check if config file was generated in the "config" folder of your server? There should be a file named "chickensshed.json5"

**Comment by holmraven** [comment]
Also I would suggest you trying to update both forge and cloth config api to see if the issue still persists.

**Comment by EJFores** [comment]
Updating to the latest version of cloth config resolved the issue. Thank you.
