### ISSUE TITLE
[Feature Request] Realistic Chicken Behaviour

### ISSUE THREAD

**Issue by EnderGirl1500** [holmraven/ChickensShed#4]
[This could be added to this mod or created separately since it doesn't have much to do with the original mod's purpose]

I was playing my survival with this wonderful mod when I realized vanilla chickens do not give eggs when breeding, they directly have their babies.

My request consists on making chickens give eggs when breeded (useful for when you need more eggs but you don't want to create a farm, which is my case) and to make the eggs laid by chickens hatchable, this means, when the item (egg) despawns, to have a probability - maybe same as vanilla - to spawn a baby.

I know this feature would change this mod completely, so I'll post this as well as a mod request on other webpages ^^

P.S.: I'd like this to be added to your mod to have both the shed and the breeding together, but I understand if you don't want to. If thats the case, please tell me if the person who makes this (if someone does) has the permission to add the shed into this "Realistic Chicken Behaviour" mod (or whatever its name would be).

**Comment by holmraven** [comment]
> [This could be added to this mod or created separately since it doesn't have much to do with the original mod's purpose]
> 
> I was playing my survival with this wonderful mod when I realized vanilla chickens do not give eggs when breeding, they directly have their babies.
> 
> My request consists on making chickens give eggs when breeded (useful for when you need more eggs but you don't want to create a farm, which is my case) and to make the eggs laid by chickens hatchable, this means, when the item (egg) despawns, to have a probability - maybe same as vanilla - to spawn a baby.
> 
> I know this feature would change this mod completely, so I'll post this as well as a mod request on other webpages ^^
> 
> P.S.: I'd like this to be added to your mod to have both the shed and the breeding together, but I understand if you don't want to. If thats the case, please tell me if the person who makes this (if someone does) has the permission to add the shed into this "Realistic Chicken Behaviour" mod (or whatever its name would be).

Hey! Thanks for the suggestion. I don't think this fits this mod, but I am in progress of developing a separate vanilla+ mod and I will kindly accept your suggestion. I will see what can be done about this somewhere after release of Minecraft 1.20.2, because currently I am busy with other stuff. Have a nice day!
