### ISSUE TITLE
[Feature Request] Backport detailed config options to 1.16.5

### ISSUE THREAD

**Issue by anoomolu** [holmraven/ChickensShed#5]
Hiya, been using ChickensShed on newer versions and it's been working great, so thank you for making this mod ^^

It's a shot in the dark but would it be possible to bring the other configurability options back to the Forge 1.16.5 version, if it's not too much hassle/effort? A tweak I've always liked using is making Turtles shed Scutes every real world hour or so, and it'd be great to have this on an older version.

No worries if you'd rather not, thanks for taking the time to read this anyways :)

**Comment by holmraven** [comment]
> Hiya, been using ChickensShed on newer versions and it's been working great, so thank you for making this mod ^^
> 
> It's a shot in the dark but would it be possible to bring the other configurability options back to the Forge 1.16.5 version, if it's not too much hassle/effort? A tweak I've always liked using is making Turtles shed Scutes every real world hour or so, and it'd be great to have this on an older version.
> 
> No worries if you'd rather not, thanks for taking the time to read this anyways :)

Hey, I have had backporting in mind and I will most likely do it, though currently I have a lack of free time. I guess its safe to say that you can expect it to be done sometime in the first half of June.
